"""Self-contained authenticated Ingress interface for the isolated lab."""

UI_HTML = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>FREE THE DECO LAB</title>
  <style>
    :root{color-scheme:dark;--bg:#08111d;--panel:#101d2d;--line:#284059;--ink:#edf7ff;--muted:#9cb1c5;--cyan:#61e7ff;--green:#67f2ad;--amber:#ffc96b;--red:#ff7586}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#14324c 0,transparent 36%),var(--bg);color:var(--ink);font:15px/1.45 system-ui,sans-serif}
    main{max-width:1050px;margin:auto;padding:24px}.hero{display:flex;gap:18px;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.eyebrow{color:var(--cyan);font-size:12px;font-weight:800;letter-spacing:.18em}.hero h1{margin:.25rem 0;font-size:clamp(29px,5vw,50px);line-height:1}.hero p{margin:.5rem 0;color:var(--muted);max-width:680px}.badge{border:1px solid var(--line);background:#0a1624;border-radius:999px;padding:9px 13px;font-weight:800;white-space:nowrap}
    .grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.card{grid-column:span 4;background:linear-gradient(150deg,#12243a,#0d1826);border:1px solid var(--line);border-radius:16px;padding:17px;box-shadow:0 15px 36px #0005}.wide{grid-column:span 8}.full{grid-column:1/-1}.label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.09em}.value{font-size:26px;font-weight:850;margin-top:4px}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}
    .checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:12px}.check{background:#081420;border:1px solid #223a51;border-radius:10px;padding:10px}.check strong{display:block}.check span{color:var(--muted);font-size:12px}
    .radio{display:flex;align-items:center;gap:20px}.radio .dial{width:92px;height:92px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(var(--cyan) 0 70%,#213348 0);border:8px solid #0a1420}.radio .dial b{font-size:28px}.route{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;gap:9px;align-items:center;margin:14px 0}.step{background:#081420;border:1px solid #29445e;border-radius:12px;padding:12px;text-align:center}.arrow{color:var(--cyan);font-size:20px}
    button{border:0;border-radius:11px;padding:11px 15px;font-weight:850;cursor:pointer;background:var(--cyan);color:#06202a}button.secondary{background:#263e55;color:var(--ink)}button.danger{background:var(--red);color:#2b0710}button:disabled{opacity:.42;cursor:not-allowed}.actions{display:flex;gap:10px;flex-wrap:wrap}.notice{color:var(--muted);margin-top:10px}.audit{margin:0;padding:0;list-style:none;max-height:230px;overflow:auto}.audit li{display:grid;grid-template-columns:145px 1fr auto;gap:9px;padding:8px 0;border-bottom:1px solid #213349;color:var(--muted)}.audit b{color:var(--ink)}
    @media(max-width:760px){main{padding:16px}.hero{display:block}.badge{display:inline-block;margin-top:8px}.card,.wide{grid-column:1/-1}.route{grid-template-columns:1fr}.arrow{transform:rotate(90deg);text-align:center}.checks{grid-template-columns:1fr}.audit li{grid-template-columns:1fr}}
  </style>
</head>
<body><main>
  <section class="hero"><div><div class="eyebrow">PACKAGE 2.0 · ISOLATED HARDWARE</div><h1>FREE THE DECO LAB</h1><p>One spare M9 Plus. One admitted radio experiment. Identity is rechecked immediately before every write and the captured baseline is restored automatically.</p></div><div id="modeBadge" class="badge">Loading…</div></section>
  <section class="grid">
    <article class="card"><div class="label">Identity gate</div><div id="identityValue" class="value">—</div><div id="identityChecks" class="checks"></div><div id="firmware" class="notice"></div></article>
    <article class="card"><div class="label">Current 2.4 GHz radio</div><div class="radio"><div class="dial"><b id="channel">—</b></div><div><div class="label">Width</div><div id="width" class="value">—</div><div id="auto" class="notice"></div></div></div></article>
    <article class="card"><div class="label">Control gate</div><div id="controlValue" class="value">—</div><p id="controlReason" class="notice"></p></article>
    <article class="card wide"><div class="label">Bounded experiment</div><div class="route"><div class="step"><b>Fresh baseline</b><br><span>identity + radio</span></div><div class="arrow">→</div><div class="step"><b>Channel 11 / HT20</b><br><span id="hold">short hold</span></div><div class="arrow">→</div><div class="step"><b>Automatic rollback</b><br><span>captured values</span></div></div><div class="actions"><button id="refresh" class="secondary">Refresh readback</button><button id="run" class="danger" disabled>Run isolated experiment</button></div><p id="message" class="notice">The first deployment is read-only. Writes must be enabled separately in App options.</p></article>
    <article class="card"><div class="label">Experiment state</div><div id="experimentState" class="value">—</div><div id="baseline" class="notice"></div><div id="candidate" class="notice"></div><div id="rollback" class="notice"></div></article>
    <article class="card full"><div class="label">Sanitized audit</div><ul id="audit" class="audit"></ul></article>
  </section>
</main>
<script>
  const $=id=>document.getElementById(id);let latest=null;
  function boolCheck(label,value){const div=document.createElement('div');div.className='check';const strong=document.createElement('strong');strong.textContent=(value?'✓ ':'✕ ')+label;strong.className=value?'ok':'bad';div.appendChild(strong);return div}
  function radioText(r){return r&&r.channel&&r.bandwidth?`Channel ${r.channel} / ${r.bandwidth}`:'not captured'}
  function render(s){latest=s;const ready=s.identity&&s.identity.ready;$('modeBadge').textContent=String(s.mode||'unknown').replaceAll('_',' ').toUpperCase();$('identityValue').textContent=ready?'VERIFIED':'BLOCKED';$('identityValue').className='value '+(ready?'ok':'bad');const checks=$('identityChecks');checks.replaceChildren();const i=s.identity||{};[['Exactly one Deco',i.single_node],['Expected spare',i.expected_identity_match],['M9 Plus model',i.model_supported],['Hardware v2',i.hardware_supported],['Controller role',i.controller_role],['Online',i.online]].forEach(x=>checks.appendChild(boolCheck(...x)));$('firmware').textContent='Firmware: '+(i.firmware_version||'not yet read');$('channel').textContent=s.radio&&s.radio.channel||'—';$('width').textContent=s.radio&&s.radio.bandwidth||'—';$('auto').textContent=s.radio?`Auto channel: ${String(s.radio.automatic_channel)} · auto width: ${String(s.radio.automatic_width)}`:'';const unlocked=Boolean(s.control_ready);$('controlValue').textContent=unlocked?'ARMED':'LOCKED';$('controlValue').className='value '+(unlocked?'warn':'ok');$('controlReason').textContent=!s.firmware_write_compatibility_acknowledged?'Firmware write compatibility has not been reviewed or acknowledged.':(!s.writes_enabled?'App options keep writes disabled.':(!ready?'Identity gate is not ready.':'One experiment is available this App start.'));$('hold').textContent=`${s.experiment.hold_seconds}s verified hold`;$('experimentState').textContent=String(s.experiment.state||'unknown').replaceAll('_',' ').toUpperCase();$('baseline').textContent='Baseline: '+radioText(s.experiment.baseline);$('candidate').textContent='Candidate: '+radioText(s.experiment.candidate_readback);$('rollback').textContent='Rollback: '+radioText(s.experiment.rollback_readback);$('run').disabled=!unlocked||['queued','preflight','applying_candidate','verifying_candidate','holding','rolling_back'].includes(s.experiment.state);const audit=$('audit');audit.replaceChildren();(s.audit||[]).slice().reverse().forEach(row=>{const li=document.createElement('li');[row.at,row.action,row.result+(row.error_code?' · '+row.error_code:'')].forEach((v,n)=>{const el=document.createElement(n===1?'b':'span');el.textContent=v||'—';li.appendChild(el)});audit.appendChild(li)})}
  async function load(){try{const r=await fetch('api/v1/status',{cache:'no-store'});render(await r.json())}catch(e){$('modeBadge').textContent='OFFLINE'}}
  $('refresh').addEventListener('click',async()=>{const r=await fetch('api/v1/refresh',{method:'POST'});const b=await r.json();$('message').textContent=b.reason;setTimeout(load,700)});
  $('run').addEventListener('click',async()=>{if(!latest||!confirm('Run the isolated Channel 11 / HT20 experiment now? The App will automatically restore the freshly captured baseline.'))return;const r=await fetch('api/v1/experiment/channel-11-ht20',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intent_token:latest.intent_token})});const b=await r.json();$('message').textContent=b.reason;setTimeout(load,500)});
  load();setInterval(load,1500);
</script></body></html>"""
